import {
    Activity,
    Airplay,
    Atom,
    Binary,
    Blocks,
    Bluetooth,
    Bot,
    Box,
    Boxes,
    Brain,
    BrainCircuit,
    Braces,
    Brush,
    Bug,
    Cable,
    Cake,
    Calculator,
    Calendar,
    Camera,
    CircuitBoard,
    Clipboard,
    Cloud,
    CloudCog,
    Code,
    Code2,
    CodeXml,
    Cog,
    Command,
    Compass,
    Component,
    Container,
    Cpu,
    Database,
    Eclipse,
    Eye,
    Feather,
    File,
    FileCode,
    FileCode2,
    FileJson,
    FileTerminal,
    FileText,
    Flame,
    Folder,
    FolderCode,
    FolderGit,
    Frame,
    Gauge,
    Globe,
    Globe2,
    GraduationCap,
    Grid3x3,
    HardDrive,
    Hash,
    Hexagon,
    Image,
    Infinity,
    Keyboard,
    Laptop,
    Layers,
    Layout,
    LayoutDashboard,
    LayoutGrid,
    Lightbulb,
    Link,
    Lock,
    Mail,
    Map,
    MessageSquare,
    Mic,
    Monitor,
    MonitorSmartphone,
    Moon,
    MousePointer,
    Network,
    Palette,
    PanelLeft,
    Pen,
    PenTool,
    Phone,
    Plug,
    Puzzle,
    QrCode,
    Radar,
    Ratio,
    Rocket,
    Ruler,
    ScanLine,
    Search,
    Server,
    Settings,
    Settings2,
    Share2,
    Shield,
    ShieldCheck,
    Smartphone,
    Sparkles,
    Square,
    SquareCode,
    Star,
    Sun,
    Swords,
    Tablet,
    Terminal,
    TestTube,
    TestTubes,
    ToggleLeft,
    Tv,
    Type,
    Unplug,
    Upload,
    Variable,
    Wand2,
    Webhook,
    Wifi,
    Wind,
    Wrench,
    Zap,
    type LucideProps,
} from 'lucide-react';
import type { ForwardRefExoticComponent, RefAttributes } from 'react';

// Map of icon name (kebab-case) → Lucide component
type IconComponent = ForwardRefExoticComponent<Omit<LucideProps, 'ref'> & RefAttributes<SVGSVGElement>>;

const iconMap: Record<string, IconComponent> = {
    // --- General / Code ---
    'code': Code,
    'code-2': Code2,
    'code-xml': CodeXml,
    'braces': Braces,
    'terminal': Terminal,
    'file-code': FileCode,
    'file-code-2': FileCode2,
    'file-json': FileJson,
    'file-terminal': FileTerminal,
    'file-text': FileText,
    'square-code': SquareCode,
    'folder-code': FolderCode,
    'variable': Variable,
    'binary': Binary,
    'hash': Hash,

    // --- Frontend ---
    'atom': Atom,
    'component': Component,
    'layout': Layout,
    'layout-grid': LayoutGrid,
    'layout-dashboard': LayoutDashboard,
    'palette': Palette,
    'brush': Brush,
    'pen-tool': PenTool,
    'pen': Pen,
    'frame': Frame,
    'type': Type,
    'image': Image,
    'ratio': Ratio,
    'grid': Grid3x3,
    'eye': Eye,
    'mouse-pointer': MousePointer,
    'panel-left': PanelLeft,
    'figma': PenTool,

    // --- Backend / Server ---
    'server': Server,
    'database': Database,
    'hard-drive': HardDrive,
    'cpu': Cpu,
    'circuit-board': CircuitBoard,
    'cog': Cog,
    'settings': Settings,
    'settings-2': Settings2,
    'wrench': Wrench,
    'plug': Plug,
    'unplug': Unplug,
    'webhook': Webhook,
    'cable': Cable,

    // --- Cloud / DevOps ---
    'cloud': Cloud,
    'cloud-cog': CloudCog,
    'container': Container,
    'box': Box,
    'boxes': Boxes,
    'blocks': Blocks,
    'layers': Layers,
    'network': Network,
    'globe': Globe,
    'globe-2': Globe2,
    'rocket': Rocket,
    'gauge': Gauge,
    'activity': Activity,

    // --- Security ---
    'shield': Shield,
    'shield-check': ShieldCheck,
    'lock': Lock,
    'scan-line': ScanLine,

    // --- AI / Data ---
    'brain': Brain,
    'brain-circuit': BrainCircuit,
    'bot': Bot,
    'sparkles': Sparkles,
    'lightbulb': Lightbulb,
    'wand': Wand2,

    // --- Testing / QA ---
    'bug': Bug,
    'test-tube': TestTube,
    'test-tubes': TestTubes,
    'clipboard': Clipboard,
    'search': Search,

    // --- Mobile / Devices ---
    'smartphone': Smartphone,
    'tablet': Tablet,
    'laptop': Laptop,
    'monitor': Monitor,
    'monitor-smartphone': MonitorSmartphone,
    'tv': Tv,
    'airplay': Airplay,

    // --- Communication ---
    'mail': Mail,
    'message-square': MessageSquare,
    'share': Share2,
    'link': Link,
    'wifi': Wifi,
    'bluetooth': Bluetooth,

    // --- Design ---
    'compass': Compass,
    'ruler': Ruler,
    'hexagon': Hexagon,
    'star': Star,
    'zap': Zap,
    'flame': Flame,
    'wind': Wind,
    'sun': Sun,
    'moon': Moon,
    'infinity': Infinity,
    'puzzle': Puzzle,

    // --- Misc ---
    'command': Command,
    'keyboard': Keyboard,
    'file': File,
    'folder': Folder,
    'folder-git': FolderGit,
    'upload': Upload,
    'camera': Camera,
    'mic': Mic,
    'phone': Phone,
    'map': Map,
    'calendar': Calendar,
    'calculator': Calculator,
    'qr-code': QrCode,
    'radar': Radar,
    'chrome': Globe,
    'eclipse': Eclipse,
    'feather': Feather,
    'swords': Swords,
    'toggle-left': ToggleLeft,
    'graduation-cap': GraduationCap,
    'cake': Cake,
    'square': Square,
};

// Curated list for the icon picker, grouped by category
export const iconPickerGroups: { label: string; icons: string[] }[] = [
    {
        label: 'Code & Development',
        icons: ['code', 'code-2', 'code-xml', 'braces', 'terminal', 'file-code', 'file-code-2', 'file-json', 'file-terminal', 'square-code', 'folder-code', 'variable', 'binary', 'hash'],
    },
    {
        label: 'Frontend & UI',
        icons: ['atom', 'component', 'layout', 'layout-grid', 'palette', 'brush', 'pen-tool', 'frame', 'type', 'image', 'ratio', 'grid', 'eye', 'mouse-pointer', 'figma', 'panel-left'],
    },
    {
        label: 'Backend & Server',
        icons: ['server', 'database', 'hard-drive', 'cpu', 'circuit-board', 'cog', 'settings', 'wrench', 'plug', 'webhook', 'cable'],
    },
    {
        label: 'Cloud & DevOps',
        icons: ['cloud', 'cloud-cog', 'container', 'box', 'boxes', 'blocks', 'layers', 'network', 'globe', 'rocket', 'gauge', 'activity'],
    },
    {
        label: 'Security',
        icons: ['shield', 'shield-check', 'lock', 'scan-line'],
    },
    {
        label: 'AI & Data',
        icons: ['brain', 'brain-circuit', 'bot', 'sparkles', 'lightbulb', 'wand'],
    },
    {
        label: 'Testing & QA',
        icons: ['bug', 'test-tube', 'test-tubes', 'clipboard', 'search'],
    },
    {
        label: 'Devices',
        icons: ['smartphone', 'tablet', 'laptop', 'monitor', 'monitor-smartphone', 'tv'],
    },
    {
        label: 'Design & Shapes',
        icons: ['compass', 'ruler', 'hexagon', 'star', 'zap', 'flame', 'wind', 'sun', 'moon', 'infinity', 'puzzle'],
    },
    {
        label: 'Miscellaneous',
        icons: ['command', 'keyboard', 'folder-git', 'chrome', 'eclipse', 'feather', 'mail', 'link', 'wifi', 'graduation-cap'],
    },
];

// All available icon names for search
export const availableIconNames = Object.keys(iconMap);

interface DynamicIconProps extends Omit<LucideProps, 'ref'> {
    /** Kebab-case icon name, e.g. "atom", "database", "code-xml" */
    name: string;
}

export function DynamicIcon({ name, ...props }: DynamicIconProps) {
    const IconComp = iconMap[name];

    if (!IconComp) {
        // Fallback to Code icon
        return <Code {...props} />;
    }

    return <IconComp {...props} />;
}
